---
title: "J1 visa waiver | How to obtain your NORI?"
date: "2017-03-14"
author: Janani Ravi
categories:
  - Resources
tags:
  - travel
  - refs
slug: j1-visa-waiver-nori
output:
  blogdown::html_page:
    toc: true
summary: "This post describes, in detail, the process of getting a J1 visa waiver and a No Obligation to Return to India (NORI) certificate from the Indian & US governments."
---

# About Me
I’m Janani Ravi, currently at Michigan State University.
### Contact:
Email: http://scr.im/janani | Twitter: [@janani137](twitter.com/janani137)

# Why I’m writing this
I went through this rather painful & ghastly process from Rutgers University, Newark, NJ. My closest consulate was the one in New York (CGNY).
I am originally from Chennai, Tamil Nadu (India). So, most of the state department and RPO/police verification guidelines I've enlisted below worked for my specific case. Folks from other countries can skip ahead from their consulate to the last step reading some country-specific blogs in-between.

# The initial process, where you read and imbibe!
## Helpful links:
* **US govt. websites**
    * http://travel.state.gov/content/visas/english/study-exchange/student/residency-waiver.html
        * http://travel.state.gov/content/visas/english/study-exchange/student/residency-waiver/ds-3035-instructions.html
    * https://j1visawaiverrecommendation.state.gov
        * https://j1visawaiverrecommendation.state.gov/accessController.asp?page=26
        * https://j1visawaiverrecommendation.state.gov/cancelHandler.asp
* **Blogs**
    * http://www.sameetmehta.com/2015/01/the-j1-waiver-process-for-indian.html 
    * https://sciash.wordpress.com/2016/03/20/j1-waiver-step-by-step-guide/ 
    * http://www.immihelp.com/forum/showthread.php/113424-J1-visa-home-residency-requirement-waiver-from-India
    * http://j1.aruppukottai.net/ (old 2009)
    * http://prashanth-jaikumar.blogspot.com/2010/05/how-i-learned-to-stop-worrying-and-love.html (2010 May)
    * *Tip*: Find specific blogs for your state since the rules and guidelines might be somewhat different. Mine was Tamil Nadu.
    * Other useful PDFs that may include some of the above: The_process

# Approximate order of key events & things-to-do
* Read & decipher the resources. It’s a one-time thing. So, do it!
* Start at least 1–1.5yrs before your current employment ends/your extended J1 expires. The process takes time & patience. Give time for ‘worst case scenarios’!
* Tip: Talk to your department admin and your university’s international/J1 office.
* Note: First extend your J1 & then apply for the waiver. You can’t extend once you apply for your waiver.
* Notarization of your biodata and affidavit (your local bank or other notary publics)
* Attestation of your biodata and affidavit: Local Indian consulate with the necessary documents
    *  Some require passport-sized photo taken within the last 6 mo (CGNY did ‘require' but they didn’t ’need' it!!)
    * Call to get their full list and check their website before going
* Send your packages to the 3 departments back home (web portal/postal mail w/ tracking)
* Back to the local Indian consulate
    * Take your 3 NORIs and forms to get a NORI that they will forward to the Department of State, US)
* Send your package to USCIS (w/ tracking)
    * Include all the necessary background documents
    * NORIs from all of the above
    * DS-3035 form
    * Preferably, don’t include what’s not in the govt. list
* Note: You can migrate your J1 to a different university during your J1’s duration of validity.
    * Talk to both the universities’ J1 departments.
    * This would take 24-48h but can only happen before you terminate your current appointment. Once you are out, you need to process a new J1 and, possibly, go this whole process once again!
    * This could happen even while your J1 is being petitioned.

# Initial set of documents needed for the Indian Consulate attestation
* Original Passport + Visa (+ copy)
* All DS-2019s (+ copy)
* Latest I-94 (+ copy)
    * https://i94.cbp.dhs.gov/I94
* Proof of residence in the US (preferably 2)
* Cash, money order or cashier’s cheque
* Biodata & Affidavit
    * unfilled sample: J1-waiver-biodata-affidavit-NY_unfilled.pdf
    * The first page is for New York Consulate General but others could use it as a guide too.

# Documents to be sent to Indian Home Department
Govt. of India Ministry of Human Resource Development (HRD)
No Obligation to Return to India
http://www.nori.ac.in/ (quite straightforward; trackable (!); they are really fast & responsive)
* Biodata and Affidavit (Notarized & Attested by the Consulate General of India, New York, USA)
* e-Copy of Passport (New and Old) and J1-Visa
* e-Copy of all DS-2019s
* e-Copies of PhD & BTech (other, as applicable) Degree Certificate
* I don’t remember if I included:
    * Employment letter from the department chair (I needed this somewhere)
    * Proof of current residence in the US

# Documents to be sent to the other two departments:
1. your state government
2. your Regional Passport Office (likely, where you got your first passport)

## List of documents
1. Biodata and Affidavit (Notarized & Attested by the Consulate General of India, New York, USA)
2. Copy of Passport (New and Old) and J1-Visa
3. Copy of all DS-2019s
4. Proof of current residence in the US
5. Copies of Ph.D. & B.Tech (other, as applicable) Degree Certificate
* Cover letter with your request to grant NORI
    * Your correct address & theirs (of course!) including your email ID (you never know!)
    * Where you are studying/working
    * Passport number (new and old)
    * Why you need the waiver (change of job, extending the same one, …)
    * List of attested/enclosed copies of documents
* Letter of consent from your parent saying that you have no legal obligation to return. Include these details, if possible/applicable
    * Who they are, where they are working/retired from
    * Brief family history
    * Your residential address (India)
    * Your brief educational history
    * When and why you came to the US
    * Your marital & dependent info (briefly) when applicable
    * Your current residential address in the US
    * Why you are requesting the waiver (in their words)
    * And something along these lines (sample below)
    
>	With regard to the NORI certification, I confirm that all the details
stated above are true to the best of my knowledge and all supporting documents
have been attached for your perusal (the shipping document list is on the next page).
There is no civil or criminal case against my daughter, XYZ. 
Also, she did not take any educational loan from the Indian or US governments.
Therefore, she does not have any commitments here in India for legal,
financial or personal reasons.

>	I, therefore, request you to kindly provide the necessary NORI certificate
that will help her continue working towards her professional and personal
goals in the US. The experience and expertise that she gains during her stay
there will help her serve India better in the long run.

# Addresses for mailing your packages
## TN State Department
```
The Secretary
Home (Citz II) Department
Government of Tamil Nadu
Secretariat, Fort St. George
Chennai 600 009
Tamil Nadu, India
```

## Regional Passport Office (RPO)
```
The Passport Officer
Regional Passport Office
Royala Towers No. 2 and 3, IV Floor,
Old No. 785, New No. 158, Anna Salai,
Chennai 600002
Tamil Nadu, India
```

# Additional documents required for police verification
*[At least, I needed it (Chennai, Tamil Nadu)]*

## Main letters/documents

* Consent letter and Pro Forma from the applicant's parent
* Letter from the applicant's spouse
* Biodata of the applicant

## Supporting documents

1. Applicant's: Mark sheets and certificates
    1. 10th 12th mark sheets
    2. B. Tech. degree certificate
    3. Ph.D. degree certificate
2. Applicant's: Passport and Visa
    1. Passport (front/back)
    2. J-1 Visa & Certificate of eligibility for exchange visitor (J-1) status (DS-2019)
    3. Old passport and old J1 and F1 visas
3. Applicant's: Graduate assistantship letter for PhD
4. Applicant's: Employment letter (current place of work)
5. Spouse's: Mark sheets and certificates
    1. 10th, 12th mark sheets
    2. B. Tech. degree certificate
    3. Ph.D. degree certificate
6. Applicant’s Spouse's: Passport and Visa
    1. Passport (front/back)
    2. H1B visa approval notice (I-797)
7. Applicant’s Spouse's: Employment letter (MSU)
8. Both: Marriage certificate
9. Both: Present address proof (Wells Fargo bank statement)
10. Applicant’s Parents': Chennai address proof (Ration card, gas bill)
11. Applicant’s Parents': Aadhar card

# Final set of documents to be sent to the USCIS, Department of State
* Read the [How to apply for a waiver](https://travel.state.gov/content/travel/en/us-visas/study/exchange/waiver-of-the-exchange-visitor/how-to-apply-waiver.html) page on the travel.state.gov website again.
* DS-3035 & SOR J1 waiver application packet for USCIS and Department of State
    * Application fee
        * Non-refundable — do it at the end
        * cashier’s cheque written out to ’The US Department of State’
        * Include your name and case number (from the DS-3035 barcode)
    * Waiver review division barcode
    * [Statement of reason](http://www.j1waivertips.com/sample-statement-of-reason-for-j1-visa-waiver-application-at-us-dept-of-state/) (below)
    
	>
	*Sample statement:*
	I am XYZ working at ABC as a PQR. I am currently on J1 visa sponsored by QWERTY. My J1 visa started on 7/19/2013 and ends on 7/19/2018 with a two-year home residency requirement. The main purpose of my J1 visa is to allow me to do research. My research work is progressing well, and it needs more time (longer than 7/19/2018) to complete my research projects. Since I am the lead person in the research projects, my employer and I feel that the opportunity for me to stay here in the US and complete the projects by obtaining the J1 visa waiver will be great.
	I am requesting a waiver of the two-year home residence requirement to complete my work here on the basis of No Objection certificate.  My home country “ABC” has no objection in allowing me to continue working here in the US, and has issued a No Objection certificate to that effect.  The ABCian Embassy in the USA will be issuing the No Objection statement to you. I kindly request you to grant me the J1 visa waiver at the earliest.

    * The actual completed DS-3035
        * https://j1visawaiverrecommendation.state.gov/
        * If you make a mistake, fill it out from the beginning
    * Passport data page
    * All DS2019s, IAP-66
    * Degree Certificates (Bachelors, Masters, PhD, …)
    * Statement of Reason
    * Two self-addressed stamped envelopes (legal-size)
    * Your NORI letters from
        * India: i) home department, ii) state department and iii) regional passport office (for police verification) and
        * US (local Indian Consulate, although they would be sending a copy)

## Address for the package to be sent

```
Postal Service
Department of State J-1 Waiver
P.O. Box 979037
St. Louis, MO 63197-9000


Courier Service
Department of State J-1 Waiver
P.O. Box 979037
1005 Convention Plaza
St. Louis, MO 63101-1200
```

## Tracking progress
https://j1visawaiverrecommendation.state.gov/

