---
title: Launching R-Ladies East Lansing!
author: Janani Ravi
date: '2018-03-01'
categories:
  - R-Ladies
tags:
  - rladies
  - software-tools
slug: rladies-elansing
output:
  blogdown::html_page:
    toc: false
summary: "Welcome to our new chapter: *Who we are & What we do.*"
---


## *Welcome to our new chapter!*

## What we're about
R-Ladies East Lansing welcomes members of all R proficiency levels, whether you are a new or aspiring R user, or an experienced R programmer interested in mentoring, networking & expert upskilling. Our non-profit, civil society community is designed to develop our members' R skills & knowledge through social, collaborative learning & sharing. Supporting minority identity access to STEM skills & careers, the Free Software Movement, and contributing to the global R community!

A local chapter of R-Ladies Global, **R-Ladies East Lansing** exists to promote gender diversity in the R community worldwide. We are pro-actively inclusive of queer, trans, and all minority identities, with additional sensitivity to intersectional identities. Our priority is to provide a safe community space for anyone identifying as a minority gender who is interested in and/or working with R. As a founding principle, there is no cost or charge to participate in any of our R-Ladies communities around the world.

We are part of Global R-Ladies group. Here are some links! You can access our presentations, R scripts and more (soon) on our Github account and follow us on twitter to stay up to date about R-Ladies news!

## Where to find us?
* [R-Ladies Global](https://www.rladies.org)
	* Github: [\@rladies](https://github.com/rladies)
	* Twitter: [\@RLadiesGlobal](http://twitter.com/RLadiesGlobal)
	* Email: info [at] rladies [dot] org
* R-Ladies East Lansing
	* Twitter: [\@RLadiesELansing](http://twitter.com/RLadiesELansing)
	* [Meetup](https://meetup.com/rladies-east-lansing/)
	* [Slack](https://rladies-eastlansing.slack.com)
	* E-mail:
		* eastlansing [at] rladies [dot] org
		* janani [at] rladies [dot] org

## *PS* Community Policies & Code of Conduct:
The leadership, mentoring & teaching roles within this Community are held exclusively by minority genders (majority gender speakers may be allowed/invited as one-off guests in exceptional circumstances at the leadership team's discretion). Due to unexpected demand, we have opened learning participation to all genders, dependent on initial and on-going vetting by the leadership team. However, the stated priority of the R-Ladies communities is the development & support specifically of those identifying as a minority gender, and we, therefore, reserve the right to guard this interest through whatever measures the leadership team deems appropriate. Anyone involved with R-Ladies East Lansing is expected to fully respect each other, the mandate of this community, and the goodwill on which R-Ladies is founded, or face expulsion/a penalty of any form, at the discretion of the leadership team. Full community guidelines are found here: https://github.com/rladies/starter-kit/wiki

## *PPS* Photos, Films and all other media/recordings:
Photos, Films, and all other media/recordings: photographs and/or video/other media will be taken at events held by this community. By taking part in an R-Ladies East Lansing event you grant the community organizers full rights to use the images resulting from the photography/video filming/media, and any reproductions or adaptations of the images for publicity, fundraising or other purposes to help achieve the community’s aims. This might include (but is not limited to), the right to use them in their printed and online publicity, social media, press releases and funding applications. If you do not wish to be recorded in these media please inform a community organizer.
