---
title: Useful Git/GitHub links
author: Janani Ravi
date: '2018-05-03'
categories:
  - Git
tags:
  - Git
  - GitHub
  - refs
slug: useful-git-github-links
output:
  blogdown::html_page:
    toc: true
---

## See also:
* 2018-04-27 — My simply Git Cheatsheet
* 2018–earlier — R Note Links
* 2018-03-15 — Creating Jekyll page on GitHub
* 2017-12-25 — Excuse me, do you have a moment to talk about version control?
* 2017-08-06 — Krishnan Lab | Source code, Data, & Code review

2017-02-11 (Check my [tweet](https://twitter.com/janani137/status/926516970920562688) as well.)

# Git
* Version control with [Git on Software Carpentry](http://swcarpentry.github.io/git-novice/)
* [Git workflow for beginners](https://sklise.com/2012/10/07/git-workflow-beginner/)
* [Mozilla Git](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/)
* [Getting started with Git](http://guides.beanstalkapp.com/version-control/getting-started-with-git.html)
* [Git, the simple guide](http://rogerdudler.github.io/git-guide/)
* [Git exercises](https://github.com/cbattista/learn-github/wiki/Learn-Github-Exercises)
* [GitHowTo](https://githowto.com/)
* [Introduction to Git and command line](https://sklise.com/2012/09/22/introduction-to-git/)
* [Friendly introduction to Git, Jane](https://kirstiejane.github.io/friendly-github-intro/)
* [Git for humans, slides by Bartlett](https://speakerdeck.com/alicebartlett/git-for-humans)
* [Learn Git branching](http://learngitbranching.js.org)
* [Git cheat sheet and best practices](https://medium.freecodecamp.com/git-cheat-sheet-and-best-practices-c6ce5321f52)
* [Getting yourself out of a Git mess](http://ohshitgit.com)
* [Try Git](https://try.github.io)

# Git and GitHub
* [GitHub tutorial, Broman](https://github.com/kbroman/github_tutorial)
* [New GitHub repo](https://github.com/new)
* [Git & Github | Seankross](http://seankross.com/the-unix-workbench/git-and-github.html)
* [GitHub on Mac](https://mac.github.com/help.html)

# R and Git
* [R with Git and GitHub](http://happygitwithr.com/big-picture.html)

# GitHub Pages, Gists | Jekyll
* Github pages [#1](https://guides.github.com/features/pages/) [#2](https://pages.github.com/)
* [Creating gists on Github](https://help.github.com/categories/gists/)
* [Jekyll](https://jekyllrb.com/docs/installation/)
* [GCC](https://gcc.gnu.org/install/)
* [Ruby](https://www.ruby-lang.org/en/downloads/)
* [Ruby Gems](https://rubygems.org/pages/download)

# Hugo, Blogdown and Git
* [Updating your website using Hugo & Blogdown, by Daijiang Li](https://daijiang.name/en/2017/03/30/updating-website-with-hugo-and-blogdown/)
