---
title: Launching R-Ladies East Lansing!
author: Janani Ravi
date: '2018-07-01'
categories:
  - R-Ladies
tags:
  - rladies
  - software-tools
slug: rladies-elansing
output:
  blogdown::html_page:
    toc: false
summary: "Welcome to our new chapter: *Who we are & What we do.*"
---

## *Welcome to our new chapter!*

## What we're about
*R-Ladies East Lansing* is a local chapter of R-Ladies Global. We meet to discuss, learn, teach, present, work on all things R! Our priority is to provide a safe community space for anyone identifying as a minority gender who is interested in and/or working with R. The group exists to promote gender diversity in the R community worldwide. We are pro-actively inclusive of queer, trans, and all minority identities, with additional sensitivity to intersectional identities.

## Who should join?
R-Ladies East Lansing welcomes members of **all R proficiency levels**, whether you are a new or aspiring R user, or an experienced R programmer interested in mentoring, networking & expert upskilling. Our non-profit, civil society community is designed to develop our members' R skills & knowledge through social, collaborative learning & sharing. *Supporting minority identity access to STEM skills & careers, the Free Software Movement, and contributing to the global R community!*

*Anyone and everyone interested in R/Data Science* should join our group and participate/contribute in any way you can, be they learners, teachers, developers or innovators! We encourage women and minority genders to present/lead most sessions, conversations but we have *no restrictions* whatsoever when it comes to membership, participation, and discussions. So, please join us and bring your R-family & R-friends!

## How to be in touch?
Access our presentations, R scripts and more on [Github](//github.com/rladies-eastlansing) and follow us on twitter to stay up to date about R-Ladies news! *Join the [Meetup group](https://meetup.com/rladies-east-lansing/) to be notified of the first meeting in July!*

* [R-Ladies Global](https://www.rladies.org)
	* Meetup: <https://meetup.com/rladies-east-lansing/>
		* Twitter: [\@RLadiesELansing](http://twitter.com/RLadiesELansing) & [\@RLadiesGlobal](http://twitter.com/RLadiesGlobal)
	* Slack: <https://rladies-eastlansing.slack.com>
	* Github: [\@rladies-eastlansing](https://github.com/rladies-eastlansing) & [\@rladies](https://github.com/rladies)
	* E-mail:
		* eastlansing [at] rladies [dot] org
		* janani [at] rladies [dot] org
		* info [at] rladies [dot] org

## Organizers
[Janani Ravi](janani@msu.edu) & [Camille Archer](archerc5@msu.edu)

## *PS* Community Policies & Code of Conduct:
Full community guidelines are found here: https://github.com/rladies/starter-kit/wiki
