---
title: 'Join us!'
author: Janani Ravi
date: '2019-01-15'
# categories:
#   - R-Ladies
tags:
  - jobs
  - evolution
  - datascience
  - bioinformatics
  - R
slug: joinus-2019
output:
  blogdown::html_page:
    toc: true
summary: "Looking for undergrads, graduate students & visiting scientists!"
---

# Research program
Our research involves developing computational approaches that can leverage large-scale genomic data to gain actionable insights into infectious disease biology.
Specifically, we focus on three key areas:

i) Identifying genomic signatures, functions, and mechanisms relevant to host-pathogen interactions, to enable understanding and guide diagnosis,
ii) Unraveling molecular mechanisms common between genetic and infectious diseases, to guide targeted drug repurposing, and
iii) Developing tools and resources for seamlessly relating sequence, structure, and function of genes/proteins in poorly characterized pathogens to enable and guide better prevention, diagnostic and treatment regimen.

# Keywords
Computational Biology | Bioinformatics | Phylogenetics & Molecular Evolution | Comparative pathogenomics | Molecular drug/vaccine discovery | Data Analysis & Visualization

# Join us
## Undergraduate Student Research
We are looking for two highly motivated and quantitatively-minded undergraduate students to work on a research project developing computational approaches to accelerate drug-/vaccine-target discovery against infectious diseases.
We are happy to train them in many aspects of data-intensive biology. A background in bioinformatics, computational biology, statistics/biostatistics, computer science, genetics, or related fields would be a perfect fit. Having programming experience in R, Python, Perl, and/or C/C++ is a huge plus.

As part of this project, they will have the opportunity to work closely with a senior scientist and learn to: a) work with large datasets, b) write structured, well-documented code to analyze, integrate, and visualize these datasets, c) interpret the results in the context of pathogenesis, and d) communicate the results in the form of a paper and presentation.

We have high expectations for their level of commitment to research, and we are keen on incorporating their contributions into co-authored papers in conferences/journals. As an undergraduate student, if you are interested in discussing research opportunities, please send me [an email](https://jananiravi.github.io/#contact) to set up a time to talk.

## Graduate Student Research
We are looking for a highly motivated Masters student who is looking to do an internship or a long-term project (6mo–1yr) in developing computational approaches to accelerate drug-/vaccine-target discovery against infectious diseases. You will be a perfect fit if you have a background in bioinformatics, computational biology, statistics/biostatistics, computer science, genetics, or related fields. Having programming experience in R, Python, Perl, and/or C/C++ is a huge plus. In addition to these technical qualifications, we are looking for someone who can work well in a team, work hard, and give/take constructive feedback.

This research experience will give you the opportunity to i) use data analysis and visualization to address key biological questions as pertaining to molecular evolution, diagnosis, and treatment (using R), ii) present at group meetings, journals, technical workshops and conferences, iii) develop high coding standards for writing efficient, clear, well-documented, version-controlled code, iv) equip yourself professional for your next career step.

*Start a conversation*
Please send me your latest CV and a cover letter that includes i) a summary of your academic/work experience, ii) description of relevant coursework, research experience (incl. publications, conference talks/posters), iii) a brief note on familiarity in the field of phylogenetics, molecular evolution, and comparative pathogenomics, iv) coding experience, if any. If you are already at MSU, please [email me](https://jananiravi.github.io/#contact) to set a time to meet and discuss your interest.

## Visiting Scientist
We welcome visiting scientists to come and collaborate with us for a short period (summer/6mo). If you have a burning question or an interesting idea that is directly related to or complements our research project(s), we would be glad to share our space, experience, and resources with you to develop your project and execute it. Having your own funding would be the easiest way to make this happen. There are some funding sources that you can apply to (e.g., [CoB](http://www.biologists.com/travelling-fellowships/)). Please send me an email to discuss this opportunity.

## Collaboration
If you are interested in any of our specific areas of research or have other great ideas that we could work on together, email me right away!

[Contact details](https://jananiravi.github.io/#contact)